config/routes.rb
Rails.application.routes.draw do

  resources :posts
  get 'sessions/new'

  get 'users/new'

  get 'users/new'

  root 'posts#index'

  get 'about' => 'static_pages#about'

  get 'backdoor' => 'sessions#new'

  get 'login' => 'sessions#new'
  post'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  resources :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }
  
  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def slug_parse
    slug.downcase.gsub(" ", "-")
  end

  def to_param
    "#{slug_parse}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_slug(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :slug, :content, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end


  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>lefurjah.me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:600&subset=latin,greek' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "lefurjah.me", root_path, id: "logo", class: "navbar-brand" %>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li><%= link_to "about",   about_path %></li>
            <%if logged_in? %>
            <li><%= link_to "log out", logout_path %><li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
        </div><!--/.nav-collapse -->
  </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=>'input-xlarge' %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug,:class=>'input-xlarge' %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :id=>'textarea' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%if logged_in? %>
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>newz</h1>
  <% @posts.each do |post| %>

      <h2><%= link_to post.title, post %></h2>
      <p><%= post.created_at.strftime('%m.%d.%Y')%></p>
      <% if post.image.exists? === true%>
      <%= image_tag post.image.url(:large) %>
      <% end %>
      <p><%= markdown(post.content) %></p>
      <%if logged_in? %>
      <div class="centered">
        <p class="blog-edit"><%= link_to 'Show', post %></p>
        <p class="blog-edit"><%= link_to 'Edit', edit_post_path(post) %></p>
        <p class="blog-edit"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
      <% end %>
  <% end %>

app/views/posts/new.html.erb
<%if logged_in? %>
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
<% end  %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @post.title %></h2>
</p>
<p>
<%= image_tag @post.image.url(:large) %>
</p>
<p>
  <%= markdown(@post.content) %>
</p>

<%if logged_in? %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<% end %>

app/views/static_pages/about.html.erb
<h1>about</h1>
<p>My name is Justin LeFurjah. This is my home on the web, currently under development.
<br>
<br>
<p><a style="text-decoration:underline" href="mailto:lefurjah@gmail.com">Contact</a>: lefurjah-at-gmail</p>
<p><a style="text-decoration:underline" href="http://www.twitter.com/lefurjah">Twitter</a>: @lefurjah</p>
<p><a style="text-decoration:underline" href="https://github.com/interestinall">Git account</a>: includes this site and more.  </p>
<p><a style="text-decoration:underline" href="https://www.linkedin.com/in/lefurjah">LinkedIn</a>: my cv</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p> Welcome <%= @user.name %> </p>

<p>You're looking handsome today.</p>

<td><%= link_to 'make a new post', new_post_path(@user) %></td>